let currentReceiptTxn = null;

function openReceipt(txn) {
  currentReceiptTxn = txn;
  const mine = cachedAccounts[0] || {};
  const isOut = txn.type === "withdrawal";
  const wrap = document.createElement("div");
  wrap.className = "modal-backdrop";
  wrap.id = "receipt-backdrop";
  wrap.onclick = (e) => { if (e.target === wrap) closeReceipt(); };
  wrap.innerHTML = `
    <div class="modal wide fade-in">
      <button class="modal-close" onclick="closeReceipt()">✕</button>
      <div class="receipt" id="printable-receipt">
        <div class="receipt-head">
          <div>
            <div class="brand">VeeraBank</div>
            <div style="font-size:10px; color:#6b6656; margin-top:2px;">Digital transaction receipt</div>
          </div>
          <div class="status">${txn.type}</div>
        </div>
        <div class="receipt-amount ${isOut ? 'neg' : 'pos'}">${isOut ? '−' : '+'}$${fmtMoney(txn.amount)}</div>
        <div class="receipt-sub">Balance after this transaction: $${fmtMoney(txn.balance_after)}</div>

        <div class="receipt-row"><span class="k">Transaction ID</span><span class="v">${txn.transaction_id || '—'}</span></div>
        <div class="receipt-row"><span class="k">Date &amp; time</span><span class="v">${fmtWhen(txn.created_at)}</span></div>
        <div class="receipt-row"><span class="k">Account holder</span><span class="v">${mine.owner_name || currentUser.full_name}</span></div>
        <div class="receipt-row"><span class="k">Account number</span><span class="v">${mine.account_number || '—'}</span></div>
        <div class="receipt-row"><span class="k">Email on file</span><span class="v">${currentUser.email}</span></div>

        <div class="receipt-foot">GENERATED BY VEERABANK · KEEP THIS RECEIPT FOR YOUR RECORDS</div>
      </div>
      <div class="modal-actions" style="display:flex; gap:10px; margin-top:16px;">
        <button class="btn" style="flex:1" onclick="downloadReceipt()">Download receipt</button>
        <button class="btn ghost" style="flex:1" onclick="printReceipt()">Print</button>
      </div>
    </div>
  `;
  document.body.appendChild(wrap);
  playModalIn("#receipt-backdrop");
}
function closeReceipt() {
  const el = document.getElementById("receipt-backdrop");
  if (el) el.remove();
  currentReceiptTxn = null;
}
function printReceipt() { window.print(); }

function downloadReceipt() {
  const txn = currentReceiptTxn;
  if (!txn) return;
  if (!window.jspdf) { toast("PDF library still loading — try again in a second, or use Print instead.", false); return; }
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ unit: "pt", format: [340, 540] });
  const mine = cachedAccounts[0] || {};
  const isOut = txn.type === "withdrawal";

  doc.setFillColor(244, 241, 234);
  doc.rect(0, 0, 340, 540, "F");

  doc.setTextColor(17, 17, 17);
  doc.setFont("times", "bold"); doc.setFontSize(18);
  doc.text("VeeraBank", 26, 44);
  doc.setFont("helvetica", "normal"); doc.setFontSize(9);
  doc.setTextColor(107, 102, 86);
  doc.text("Digital transaction receipt", 26, 58);
  doc.setDrawColor(184, 178, 162);
  doc.setLineDashPattern([2, 2], 0);
  doc.line(26, 70, 314, 70);

  doc.setFont("times", "bold"); doc.setFontSize(28);
  doc.setTextColor(...(isOut ? [179, 57, 47] : [23, 122, 83]));
  doc.text(`${isOut ? "-" : "+"}$${fmtMoney(txn.amount)}`, 170, 112, { align: "center" });
  doc.setFont("helvetica", "normal"); doc.setFontSize(9);
  doc.setTextColor(107, 102, 86);
  doc.text(`Balance after: $${fmtMoney(txn.balance_after)}`, 170, 128, { align: "center" });

  const rows = [
    ["Transaction ID", txn.transaction_id || "-"],
    ["Type", (txn.type || "-").toUpperCase()],
    ["Date & time", fmtWhen(txn.created_at)],
    ["Account holder", mine.owner_name || currentUser.full_name],
    ["Account number", mine.account_number || "-"],
    ["Email on file", currentUser.email],
  ];
  let y = 160;
  doc.setLineDashPattern([1, 1], 0);
  rows.forEach(([k, v]) => {
    doc.setFont("courier", "normal"); doc.setFontSize(9); doc.setTextColor(107, 102, 86);
    doc.text(k, 26, y);
    doc.setFont("courier", "bold"); doc.setTextColor(17, 17, 17);
    doc.text(String(v), 314, y, { align: "right" });
    doc.setDrawColor(216, 210, 194);
    doc.line(26, y + 6, 314, y + 6);
    y += 26;
  });

  doc.setFont("helvetica", "normal"); doc.setFontSize(7.5);
  doc.setTextColor(138, 133, 112);
  doc.text("GENERATED BY VEERABANK · KEEP THIS RECEIPT FOR YOUR RECORDS", 170, 510, { align: "center" });

  doc.save(`veerabank-receipt-${(txn.transaction_id || "txn").slice(0,8)}.pdf`);
  toast("Receipt downloaded.");
}
