apiVersion: v1
kind: Service
metadata:
  name: support-tickets-svc
  namespace: veerabank
spec:
  type: ClusterIP
  selector:
    app: support-tickets
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
